frontend/components/mypage/NicknameContainer.tsx, frontend/mocks/data/members.js, frontend/mocks/handlers/members.js, frontend/mocks/servers.js, frontend/mocks/workers.js, frontend/pages/index.tsx, frontend/pages/mypage.tsx, frontend/stores/useMembers.ts
=> 마이페이지 컴포넌트 구현 (#18)

frontend/components/main/RoomEnterForm.tsx, frontend/pages/index.tsx, frontend/public/static/fonts/style.css, frontend/stores/useMembers.ts, frontend/styles/components/Button.ts, frontend/styles/components/Form.ts, frontend/styles/components/Frame.ts
- related #25 
- close #25 
- 재사용되는 디자인 컴포넌트들 `styles`에 넣어놨습니다.
=> 메인 페이지 디자인 (#25)

frontend/.babelrc, frontend/components/main/RoomEnterForm.tsx, frontend/package.json, frontend/pages/_document.tsx, frontend/pages/index.tsx, frontend/yarn.lock
#37 
- styled-components SSR 적용 세팅해뒀으니 yarn 한번 받아주세요.
- [관련 링크](https://juni-official.tistory.com/205)
=> 메인 페이지 디자인 수정 (#37)

backend/text-me/src/main/java/domain/letter/controller/LetterController.java, backend/text-me/src/main/java/domain/letter/dto/request/LetterRequest.java, backend/text-me/src/main/java/domain/letter/dto/response/LetterResponse.java, backend/text-me/src/main/java/domain/letter/entity/Letter.java, backend/text-me/src/main/java/domain/letter/exception/LetterNotFoundException.java, backend/text-me/src/main/java/domain/letter/repository/LetterRepository.java, backend/text-me/src/main/java/domain/letter/service/LetterService.java, backend/text-me/src/main/java/domain/security/jwt/JwtAuth.java, backend/text-me/src/main/java/error/ErrorCode.java, backend/text-me/src/main/resources/application.yml
=> Letter 관련 API 생성 (#48)

frontend/pages/[uid]/write/preview-card-picture.tsx, frontend/pages/[uid]/write/send-complete.tsx, frontend/pages/signin.tsx
- 닉네임 글자수 제한 부분에서 되긴 하는데 오류가 떠서 한번 확인해주세요
=> feature: 편지 작성 완료 컴포넌트 구현(#51)

frontend/pages/[uid]/write/send-complete.tsx
=> 빌드 에러 해결 (#73)

backend/text-me/src/main/java/gifterz/textme/domain/user/controller/UserController.java, backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
=> 사용자 정보 조회(#83)

backend/text-me/src/main/java/gifterz/textme/domain/user/controller/UserController.java, backend/text-me/src/main/java/gifterz/textme/domain/user/entity/User.java, backend/text-me/src/main/java/gifterz/textme/domain/user/repository/UserRepository.java, backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
=> 사용자 이름 수정 (#88, #92)

backend/text-me/src/main/java/gifterz/textme/domain/card/controller/CardController.java, backend/text-me/src/main/java/gifterz/textme/domain/card/service/CardService.java, backend/text-me/src/main/java/gifterz/textme/s3Proxy/S3Service.java
=> 카드 전체 조회 (#97)

.github/workflows/build-backend.yml
도커 push 과정에서 도커 이미지 테크를 추가해주는 스크립트를 추가
=> 도커 이미지 tag 수정 (#65)

.github/workflows/build-backend.yml
도커 push 과정에서 도커 이미지 테크를 추가해주는 스크립트를 추가
=> 도커 이미지 tag 수정

frontend/auth/api.ts, frontend/mocks/setMocking.js, frontend/pages/[uid]/write/select-card-picture.tsx
=> 환경변수를 세팅(#81)

backend/text-me/src/main/java/gifterz/textme/domain/user/controller/UserController.java, backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
=> 이메일을 사용해 사용자 정보 조회 (#110)

backend/text-me/src/main/java/gifterz/textme/domain/user/controller/UserController.java, backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
=> feat: 사용자 id를 사용해 사용자 정보 조회 (#112)

backend/text-me/src/main/java/gifterz/textme/domain/card/service/CardService.java
=> 카드 url 전체 조회 (#114)

backend/text-me/src/main/java/gifterz/textme/domain/card/entity/Card.java, backend/text-me/src/main/java/gifterz/textme/domain/entity/BaseEntity.java, backend/text-me/src/main/java/gifterz/textme/domain/entity/StatusType.java, backend/text-me/src/main/java/gifterz/textme/domain/letter/entity/Letter.java, backend/text-me/src/main/java/gifterz/textme/domain/security/entity/RefreshToken.java, backend/text-me/src/main/java/gifterz/textme/domain/user/entity/User.java
=> feat: 상태데이터를 추가 (#117)

frontend/auth/visitorApi.ts, frontend/auth/visitor_api.ts, frontend/components/mypage/NicknameContainer.tsx, frontend/components/room/Letter.tsx, frontend/components/room/LetterView.tsx, frontend/pages/[uid]/index.tsx, frontend/pages/[uid]/write/select-card-picture.tsx, frontend/pages/[uid]/write/send-complete.tsx, frontend/pages/[uid]/write/write-letter.tsx, frontend/pages/signin.tsx, frontend/pages/signup.tsx, frontend/stores/useCardPicture.ts, frontend/stores/useLetterView.ts, frontend/stores/useLetters.ts, frontend/stores/useMembers.ts, frontend/stores/useRoomEnter.ts, frontend/stores/useRoomInfo.ts, frontend/stores/useSendLetter.ts, frontend/types/index.ts
빠뜨린 부분이나 이상하게 수정한 부분 있으면 지적해주세요 바쁘시겠지만 ..
relate #106
=> API 수정(#106)

backend/text-me/src/main/java/gifterz/textme/domain/security/WebConfig.java
=> CORS해결 (#120)

backend/text-me/Dockerfile
- Jib 빌드로 인해 불필요해진 도커 파일을 삭제하였습니다.
=> 도커 파일 삭제 (#65)

.github/workflows/build-backend.yml, .github/workflows/deploy-backend.yml
AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
DB_PASSWORD : ${{ secrets.DB_PASSWORD }}
DB_URL : ${{ secrets.DB_URL }}
DB_USERNAME : ${{ secrets.DB_USERNAME }}
JWT_EXPIRY : ${{ secrets.JWT_EXPIRY }}
JWT_KEY : ${{ secrets.JWT_KEY }}
REFRESH_EXPIRY: ${{ secrets.REFRESH_EXPIRY }}
=> 백엔드 빌드 스크립트 환경변수 추가 (#132)

backend/text-me/src/main/java/gifterz/textme/domain/security/WebConfig.java
=> fix: CORS해결 (#135)

frontend/components/room/Background.tsx
=> 배경 반응형 계산 (#107)

frontend/components/main/RoomEnterForm.tsx, frontend/components/room/ButtonsContainer.tsx, frontend/components/room/Letter.tsx, frontend/components/room/ShareModal.tsx, frontend/pages/[uid]/index.tsx, frontend/pages/[uid]/write/select-card-picture.tsx, frontend/pages/index.tsx, frontend/pages/mypage.tsx, frontend/pages/signin.tsx, frontend/stores/useCardPicture.ts, frontend/stores/useMembers.ts, frontend/stores/useRoomEnter.ts, frontend/styles/components/Button.ts
=> 예외 상황 핸들링 (#153)

frontend/pages/[uid]/write/select-card-picture.tsx
=> 이미지 업로드 최대 길이 제한(#236)

frontend/pages/[uid]/write/select-card-picture.tsx
=> 사진 사이즈 조절(#236)

backend/text-me/src/main/java/gifterz/textme/domain/oauth/entity/OauthMember.java, backend/text-me/src/main/java/gifterz/textme/domain/oauth/kakao/config/HttpInterfaceConfig.java, backend/text-me/src/main/java/gifterz/textme/domain/oauth/kakao/controller/KakaoApi.java, backend/text-me/src/main/java/gifterz/textme/domain/oauth/kakao/dto/KakaoMemberResponse.java, backend/text-me/src/main/java/gifterz/textme/domain/oauth/kakao/service/KakaoMemberClient.java
=> Fix: Oauth 요청관련 에러 해결

backend/text-me/src/main/java/gifterz/textme/domain/letter/controller/LetterController.java, backend/text-me/src/main/java/gifterz/textme/domain/letter/service/LetterService.java, backend/text-me/src/main/java/gifterz/textme/domain/oauth/entity/OauthMember.java, backend/text-me/src/main/java/gifterz/textme/domain/oauth/repository/OauthMemberRepository.java, backend/text-me/src/main/java/gifterz/textme/domain/oauth/service/OauthService.java, backend/text-me/src/main/java/gifterz/textme/domain/security/service/AesUtils.java, backend/text-me/src/main/java/gifterz/textme/domain/security/service/RefreshTokenService.java, backend/text-me/src/main/java/gifterz/textme/domain/user/controller/UserController.java, backend/text-me/src/main/java/gifterz/textme/domain/user/entity/User.java, backend/text-me/src/main/java/gifterz/textme/domain/user/service/UserService.java
작업내용
---
- 회원가입 api 리팩토링
- 일반 로그인 api 디미터 법칙 적용
- 사용자 정보 조회 api 리팩토링
- 사용자 이름 업데이트 api 리팩토링
- 소셜로그인 추가로 인해 id 중복 가능성으로 기존 url에 노출되던 데이터를 사용자 id 사용 대신 email 데이터 사용
- 이메일 사용한 사용자 정보 조회 api 리팩토링
- 사용자 ID 사용한 정보 조회 api 리팩토링
- Refresh토큰 재발급 api 리팩토링
- 소셜로그인 사용자 이름 변경 로직 추가
=> Refactor: 소셜로그인 추가로 인해 사용자 관련 api 리팩토링

backend/text-me/src/main/java/gifterz/textme/domain/letter/controller/LetterController.java, backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/request/EmailWithContents.java, backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/request/ReceiverInfo.java, backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/request/SlowLetterWithAddressRequest.java, backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/request/SlowLetterWithEmailRequest.java, backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/response/SlowLetterWithAddressResponse.java, backend/text-me/src/main/java/gifterz/textme/domain/letter/dto/response/SlowLetterWithEmailResponse.java, backend/text-me/src/main/java/gifterz/textme/domain/letter/entity/Address.java, backend/text-me/src/main/java/gifterz/textme/domain/letter/entity/SlowLetter.java, backend/text-me/src/main/java/gifterz/textme/domain/letter/repository/SlowLetterRepository.java, backend/text-me/src/main/java/gifterz/textme/domain/letter/service/LetterService.java
=> Feature: add send letter to me

frontend/components/slow/AddressForm.tsx, frontend/components/slow/EmailForm.tsx, frontend/components/slow/PostCodeForm.tsx, frontend/components/slow/SelectMethod.tsx, frontend/pages/slow-letter/get-info.tsx
- slow-letter/index 에서 글씨가 너무 커서 줄넘김 발생 -> h3로 변경하고 nowrap 줬어요
- slow-letter/get-info 에서 SelectContainer 내의 버튼 컴포넌트 때문에 BackHeader 컴포넌트가 영향 받아서 밖으로 뺐는데, z-index가 안먹어서 일단 이메일로 전송하는 부분에만 넣어뒀습니다
=> feat: 뒤로가기 버튼 추가

frontend/components/slow/BackHeader.tsx, frontend/components/slow/EmailForm.tsx, frontend/pages/slow-letter/get-info.tsx
- styled 상속 받을 때 스타일 컴포넌트가 아닌 일반 컴포넌트로 받아서 적용이 안됨
- 모든 컴포넌트에 z-index를 부여해야 된다는 점이 고질적인 문제라고 생각. 이 부분 전반적으로 수정해야 함
=> 헤더 z-index 에러 해결 (#288)

frontend/components/slow/AddressForm.tsx, frontend/components/slow/EmailForm.tsx, frontend/components/slow/PostCodeForm.tsx, frontend/components/slow/SelectMethod.tsx, frontend/components/write/SelectCard.tsx, frontend/pages/slow-letter/get-info.tsx, frontend/pages/slow-letter/index.tsx, frontend/public/static/images/card-alt.ts, frontend/stores/useCardPicture.ts
- 느린 우체통 배경 오버플로우 해결 (width: 100%-> inherit 변경)
- 카드 이미지 alt 속성 추가
=> 배경 오버플로우 해결 (#290)

frontend/components/slow/CardRotator.tsx, frontend/components/slow/WriteFinishBox.tsx, frontend/package.json, frontend/pages/[uid]/write/select-card-picture.tsx, frontend/pages/slow-letter/finish.tsx, frontend/yarn.lock
내 방 만들고 편지 받는 사이트로 유도하는 버튼은 아직 구현하지 않음
[BUG] 회전 이미지에 opacity가 적용되는 문제 -> 왜인지 찾을수가 없어서 일단 보류하고 푸쉬했습니당
=> 3D 회전 카드 구현

backend/text-me/src/main/java/gifterz/textme/domain/card/entity/Card.java, backend/text-me/src/main/java/gifterz/textme/domain/letter/entity/Letter.java, backend/text-me/src/main/java/gifterz/textme/domain/letter/entity/SlowLetter.java, backend/text-me/src/main/java/gifterz/textme/domain/security/entity/RefreshToken.java, backend/text-me/src/main/java/gifterz/textme/domain/user/entity/Member.java
=> Refactor: change data type

frontend/pages/dku/signin.tsx
=> fix: oauth 코드 제외
